version: "3.7"

services:
  video-renderer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      BASE_URL: https://video-renderer.pavlin.dev
    restart: unless-stopped

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - video-renderer
    restart: unless-stopped
    profiles:
      - "with-proxy"